FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install for caching
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt 

COPY backend /app/backend

RUN mkdir -p /app/backend/uploads /app/backend/flask_sessions

EXPOSE 8000

CMD ["gunicorn", "-w", "3", "-b", "0.0.0.0:8000", "backend.app:app"]
